# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'phyxableapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for phyxableapp

  target 'phyxableapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'phyxableappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'phyxableapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for phyxableapp-tvOS

  target 'phyxableapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
